# Generated by Django 5.1.3 on 2024-11-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('middle_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('last_name', models.CharField(db_index=True, max_length=50)),
                ('contact_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_index=True, max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Annulled', 'Annulled')], db_index=True, max_length=50)),
                ('birth_date', models.DateField(db_index=True)),
                ('barangay', models.CharField(db_index=True, max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('client_type', models.CharField(choices=[('Senior Citizen', 'Senior Citizen'), ('Solo Parent', 'Solo Parent'), ('PWD', 'PWD')], max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_name', models.CharField(max_length=255)),
                ('notification_message', models.TextField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification Setting',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=50)),
                ('middle_name', models.CharField(db_index=True, max_length=50)),
                ('last_name', models.CharField(db_index=True, max_length=50)),
                ('birth_date', models.DateField(db_index=True)),
                ('contact_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], db_index=True, max_length=10)),
                ('address', models.TextField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.client')),
            ],
            options={
                'verbose_name': 'Beneficiary',
                'verbose_name_plural': 'Beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance_type', models.CharField(choices=[('Medical', 'Medical'), ('Education', 'Education'), ('Burial', 'Burial')], max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=7000, max_digits=10, null=True)),
                ('is_notified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_claimed', models.BooleanField(blank=True, default=False, null=True)),
                ('date_provided', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='app.client')),
            ],
            options={
                'verbose_name': 'Assistance',
                'verbose_name_plural': 'Assistance',
            },
        ),
    ]
