# Generated by Django 5.1.3 on 2024-11-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='is_primary_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('Senior Citizen', 'Senior Citizen'), ('Solo Parent', 'Solo Parent'), ('PWD', 'PWD'), ('Student', 'Student')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='notification_message',
            field=models.TextField(default='Good morning {name}, ito po ay galing sa opisina ng MSWD Carmen pina paalalahan po namin kayo na ngayong araw po pwedi na ninyo eclaim ang cash assistance niyo para sa {assistance_type} assistance.\n\nPlease be on time po dahil hanggang 8:00 am - 12:00 pm lang po ang claim hours.\n\nHave a good day ahead,\nFrom MSWD Carmen\n    ', max_length=500),
        ),
    ]
