# Generated by Django 5.1.3 on 2024-11-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notificationsetting_is_primary_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='date_provided',
            field=models.DateField(blank=True, null=True),
        ),
    ]
