# Generated by Django 5.1.3 on 2024-11-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_assistance_date_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='is_ready',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('Senior Citizen', 'Senior Citizen'), ('Solo Parent', 'Solo Parent'), ('PWD', 'PWD')], max_length=50),
        ),
    ]
