# Generated by Django 5.1.3 on 2024-11-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_assistance_is_ready_alter_client_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Grand parent', 'Grand parent')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, help_text='Optional middle name', max_length=50, null=True),
        ),
    ]
