# Generated by Django 5.1.3 on 2024-11-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_client_relationship_type_alter_client_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='relationship_type',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Grand parent', 'Grand parent')], db_index=True, max_length=50, null=True),
        ),
    ]
