# Generated by Django 5.1.3 on 2024-12-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_assistance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('Senior Citizen', 'Senior Citizen'), ('Family Solo Parent', 'Family Solo Parent'), ('PWD', 'PWD')], max_length=50),
        ),
    ]
