# Generated by Django 5.1.3 on 2024-12-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_client_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='who_will_claim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Grand parent', 'Grand parent'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Grand child', 'Grand child'), ('Aunt', 'Aunt'), ('Uncle', 'Uncle'), ('Niece', 'Niece'), ('Nephew', 'Nephew'), ('First Cousin', 'First Cousin'), ('Cousin', 'Cousin'), ('Relative', 'Relative'), ('Spouse', 'Spouse'), ('Child', 'Child')], db_index=True, max_length=50, null=True),
        ),
    ]
